#!/bin/bash

# load this in temporary config and also in myshellconfig permanent
if [ -d "${HOME}/bin" ] ; then
    pathmunge "${HOME}/bin"
    export PATH
fi

if [ -f ~/.aliases ]; then
    . ~/.aliases
fi

export WORK=~/Work

[ -z "${USERNAME+x}" ]                  && export USERNAME="$USER"
[ -z "${USEREMAIL+x}" ]                 && export USEREMAIL="$USER@$(domainname -d)"
[ -z "${FULLNAME+x}" ]                  && export FULLNAME="$(getent passwd $USER | cut -d ":" -f 5 | cut -d ',' -f 1)"
[ -z "${GIT_AUTHOR_NAME+x}" ]           && export GIT_AUTHOR_NAME=$FULLNAME
[ -z "${GIT_AUTHOR_EMAIL+x}" ]          && export GIT_AUTHOR_EMAIL=$USEREMAIL
[ -z "${GIT_COMMITTER_NAME+x}" ]        && export GIT_COMMITTER_NAME=$FULLNAME
[ -z "${GIT_COMMITTER_EMAIL+x}" ]       && export GIT_COMMITTER_EMAIL=$USEREMAIL

turnoffbeep
